#!/bin/bash
echo "disabling samba daemons..."
services=("samba" "smbd" "nmbd" "winbind")

for service in "${services[@]}"; do
    if systemctl is-active --quiet "$service"; then
        echo "$service is active -> stopping and disabling..."
        systemctl stop "$service"
        systemctl disable "$service"
    else
        echo "$service is not active -> skipping."
    fi
done